<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7xQomU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7xQomU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7xQomU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7xQomU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH7xQomU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H7xQomU',
    'container.build_id' => 'b5a04b43',
    'container.build_time' => 1644475507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7xQomU');
